-- ============================================================
-- CHAMPIONS BOLÃO — SUPABASE SETUP
-- Execute este arquivo inteiro no SQL Editor do Supabase.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- TABLES
-- ------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  avatar_path text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists avatar_path text;

create table if not exists public.seasons (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.rounds (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete cascade,
  name text not null,
  stage text not null default 'Fase de liga',
  sort_order integer not null check (sort_order > 0),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (season_id, sort_order)
);

alter table public.rounds add column if not exists closed_at timestamptz;

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  round_id uuid not null references public.rounds(id) on delete cascade,
  home_team text not null check (length(trim(home_team)) > 0),
  away_team text not null check (length(trim(away_team)) > 0),
  selected_by_user_id uuid references public.profiles(id) on delete set null,
  kickoff_at timestamptz not null,
  home_score integer check (home_score between 0 and 99),
  away_score integer check (away_score between 0 and 99),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((home_score is null and away_score is null) or (home_score is not null and away_score is not null)),
  check (lower(trim(home_team)) <> lower(trim(away_team)))
);

alter table public.matches add column if not exists selected_by_user_id uuid references public.profiles(id) on delete set null;
create index if not exists idx_matches_selected_by_user on public.matches(selected_by_user_id);

create table if not exists public.predictions (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  home_score integer not null check (home_score between 0 and 99),
  away_score integer not null check (away_score between 0 and 99),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, user_id)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_rounds_season on public.rounds(season_id, sort_order);
create index if not exists idx_matches_round on public.matches(round_id, kickoff_at);
create index if not exists idx_matches_kickoff on public.matches(kickoff_at);
create index if not exists idx_predictions_match on public.predictions(match_id);
create index if not exists idx_predictions_user on public.predictions(user_id);
create index if not exists idx_audit_logs_created on public.audit_logs(created_at desc);

-- Only one active season at a time.
create unique index if not exists one_active_season
  on public.seasons ((is_active))
  where is_active = true;

-- ------------------------------------------------------------
-- AUTH PROFILE CREATION
-- ------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  local_name text;
  pretty_name text;
  user_role text;
begin
  local_name := lower(split_part(new.email, '@', 1));

  pretty_name := case local_name
    when 'leandro' then 'Leandro'
    when 'caio' then 'Caio'
    when 'joao' then 'João'
    when 'matheus' then 'Matheus'
    when 'leonardo' then 'Leonardo'
    when 'bruno' then 'Bruno'
    else coalesce(new.raw_user_meta_data->>'display_name', initcap(local_name), 'Jogador')
  end;

  user_role := case
    when lower(new.email) = 'leandro@champions-bolao.app' then 'admin'
    else 'user'
  end;

  insert into public.profiles (id, display_name, role)
  values (new.id, pretty_name, user_role)
  on conflict (id) do update
    set display_name = excluded.display_name;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill profiles if users were created before this SQL was executed.
insert into public.profiles (id, display_name, role)
select
  u.id,
  case lower(split_part(u.email, '@', 1))
    when 'leandro' then 'Leandro'
    when 'caio' then 'Caio'
    when 'joao' then 'João'
    when 'matheus' then 'Matheus'
    when 'leonardo' then 'Leonardo'
    when 'bruno' then 'Bruno'
    else initcap(split_part(u.email, '@', 1))
  end,
  case when lower(u.email) = 'leandro@champions-bolao.app' then 'admin' else 'user' end
from auth.users u
where not exists (select 1 from public.profiles p where p.id = u.id);

-- Ensure Leandro is admin even after a rerun.
update public.profiles p
set role = 'admin'
from auth.users u
where p.id = u.id
  and lower(u.email) = 'leandro@champions-bolao.app';

-- ------------------------------------------------------------
-- SECURITY HELPERS
-- ------------------------------------------------------------

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.match_has_started(p_match_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select now() >= kickoff_at from public.matches where id = p_match_id),
    false
  );
$$;

create or replace function public.match_is_open(p_match_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select now() < kickoff_at from public.matches where id = p_match_id),
    false
  );
$$;

-- ------------------------------------------------------------
-- DATABASE GUARDS
-- ------------------------------------------------------------

create or replace function public.guard_prediction_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  kickoff timestamptz;
begin
  if tg_op = 'UPDATE' then
    if new.user_id <> old.user_id or new.match_id <> old.match_id then
      raise exception 'Não é permitido trocar o usuário ou o jogo de um palpite.';
    end if;
    new.created_at := old.created_at;
  end if;

  if auth.uid() is not null and new.user_id <> auth.uid() then
    raise exception 'Você só pode salvar seu próprio palpite.';
  end if;

  select kickoff_at into kickoff from public.matches where id = new.match_id;
  if kickoff is null then
    raise exception 'Partida não encontrada.';
  end if;

  if now() >= kickoff then
    raise exception 'Os palpites desta partida já foram encerrados.';
  end if;

  new.updated_at := now();
  if tg_op = 'INSERT' then new.created_at := now(); end if;
  return new;
end;
$$;

drop trigger if exists guard_prediction_before_write on public.predictions;
create trigger guard_prediction_before_write
  before insert or update on public.predictions
  for each row execute function public.guard_prediction_write();

create or replace function public.guard_match_result()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at := now();

  if tg_op = 'UPDATE' and
     (new.home_score is distinct from old.home_score or new.away_score is distinct from old.away_score) then
    if (new.home_score is null) <> (new.away_score is null) then
      raise exception 'Informe os dois placares ou deixe os dois vazios.';
    end if;

    if new.home_score is not null and now() < new.kickoff_at then
      raise exception 'O resultado só pode ser informado depois do início da partida.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists guard_match_before_write on public.matches;
create trigger guard_match_before_write
  before insert or update on public.matches
  for each row execute function public.guard_match_result();

-- ------------------------------------------------------------
-- AUDIT LOG HELPERS / TRIGGERS
-- ------------------------------------------------------------

create or replace function public.log_prediction_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  match_label text;
  round_label text;
  round_identifier uuid;
  action_name text;
begin
  if tg_op = 'UPDATE' and new.home_score = old.home_score and new.away_score = old.away_score then
    return new;
  end if;

  select m.home_team || ' x ' || m.away_team, r.name, r.id
  into match_label, round_label, round_identifier
  from public.matches m
  join public.rounds r on r.id = m.round_id
  where m.id = new.match_id;

  action_name := case when tg_op = 'INSERT' then 'prediction_created' else 'prediction_updated' end;

  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
  values (
    new.user_id,
    action_name,
    'prediction',
    new.id,
    jsonb_build_object('match_name', match_label, 'round_name', round_label, 'round_id', round_identifier)
  );

  return new;
end;
$$;

drop trigger if exists log_prediction_after_write on public.predictions;
create trigger log_prediction_after_write
  after insert or update on public.predictions
  for each row execute function public.log_prediction_activity();

create or replace function public.log_round_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
  values (auth.uid(), 'round_created', 'round', new.id, jsonb_build_object('round_id', new.id, 'round_name', new.name, 'stage', new.stage, 'season_id', new.season_id));
  return new;
end;
$$;

drop trigger if exists log_round_after_insert on public.rounds;
create trigger log_round_after_insert
  after insert on public.rounds
  for each row execute function public.log_round_created();

create or replace function public.log_season_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
  values (auth.uid(), 'season_created', 'season', new.id, jsonb_build_object('season_name', new.name));
  return new;
end;
$$;

drop trigger if exists log_season_after_insert on public.seasons;
create trigger log_season_after_insert
  after insert on public.seasons
  for each row execute function public.log_season_created();

create or replace function public.log_match_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  round_label text;
  round_identifier uuid;
  match_label text;
begin
  select name, id into round_label, round_identifier from public.rounds where id = new.round_id;
  match_label := new.home_team || ' x ' || new.away_team;

  if tg_op = 'INSERT' then
    insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
    values (auth.uid(), 'match_created', 'match', new.id, jsonb_build_object('match_name', match_label, 'round_name', round_label, 'round_id', round_identifier));
  elsif new.home_score is distinct from old.home_score or new.away_score is distinct from old.away_score then
    if new.home_score is not null and new.away_score is not null then
      insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
      values (
        auth.uid(),
        'result_updated',
        'match',
        new.id,
        jsonb_build_object(
          'match_name', match_label,
          'round_name', round_label,
          'round_id', round_identifier,
          'result', new.home_score::text || ' x ' || new.away_score::text
        )
      );
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists log_match_after_write on public.matches;
create trigger log_match_after_write
  after insert or update on public.matches
  for each row execute function public.log_match_activity();

-- ------------------------------------------------------------
-- RPCs
-- ------------------------------------------------------------

create or replace function public.record_login_activity()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Não autenticado.';
  end if;

  insert into public.audit_logs (actor_user_id, action, entity_type, metadata)
  values (auth.uid(), 'signed_in', 'session', '{}'::jsonb);
end;
$$;

create or replace function public.get_prediction_presence(p_match_ids uuid[])
returns table (
  match_id uuid,
  user_id uuid,
  display_name text,
  has_predicted boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    m.id as match_id,
    p.id as user_id,
    p.display_name,
    exists (
      select 1 from public.predictions pr
      where pr.match_id = m.id and pr.user_id = p.id
    ) as has_predicted
  from public.matches m
  cross join public.profiles p
  where auth.uid() is not null
    and m.id = any(p_match_ids)
  order by m.kickoff_at, p.display_name;
$$;

create or replace function public.set_active_season(p_season_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  season_label text;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem alterar a temporada ativa.';
  end if;

  if not exists (select 1 from public.seasons where id = p_season_id) then
    raise exception 'Temporada não encontrada.';
  end if;

  update public.seasons set is_active = false where is_active = true and id <> p_season_id;
  update public.seasons set is_active = true where id = p_season_id;

  select name into season_label from public.seasons where id = p_season_id;
  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
  values (auth.uid(), 'season_activated', 'season', p_season_id, jsonb_build_object('season_name', season_label));
end;
$$;

-- ------------------------------------------------------------
-- DELETION AUDIT + ACTIVITY FEED ADMIN
-- ------------------------------------------------------------

create or replace function public.log_round_deleted()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
  values (
    auth.uid(),
    'round_deleted',
    'round',
    old.id,
    jsonb_build_object(
      'round_id', old.id,
      'round_name', old.name,
      'stage', old.stage,
      'season_id', old.season_id
    )
  );
  return old;
end;
$$;

drop trigger if exists log_round_before_delete on public.rounds;
create trigger log_round_before_delete
  before delete on public.rounds
  for each row execute function public.log_round_deleted();

create or replace function public.log_season_deleted()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
  values (
    auth.uid(),
    'season_deleted',
    'season',
    old.id,
    jsonb_build_object(
      'season_id', old.id,
      'season_name', old.name
    )
  );
  return old;
end;
$$;

drop trigger if exists log_season_before_delete on public.seasons;
create trigger log_season_before_delete
  before delete on public.seasons
  for each row execute function public.log_season_deleted();

create or replace function public.clear_activity_feed()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem limpar as atividades.';
  end if;

  delete from public.audit_logs;

  insert into public.audit_logs (actor_user_id, action, entity_type, metadata)
  values (
    auth.uid(),
    'activity_feed_cleared',
    'activity',
    jsonb_build_object('cleared_at', now())
  );
end;
$$;



-- ------------------------------------------------------------
-- ADMIN: DELETE PARTICIPANT FROM AUTH + DATABASE
-- ------------------------------------------------------------

create or replace function public.delete_participant(p_user_id uuid)
returns table (
  deleted_display_name text,
  deleted_avatar_path text
)
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor_id uuid := auth.uid();
  v_display_name text;
  v_avatar_path text;
  v_role text;
begin
  if v_actor_id is null or not public.is_admin() then
    raise exception 'Apenas administradores podem excluir participantes.';
  end if;

  if p_user_id is null then
    raise exception 'Participante inválido.';
  end if;

  if p_user_id = v_actor_id then
    raise exception 'Você não pode excluir o próprio usuário enquanto está logado.';
  end if;

  select display_name, avatar_path, role
    into v_display_name, v_avatar_path, v_role
  from public.profiles
  where id = p_user_id;

  if not found then
    raise exception 'Participante não encontrado.';
  end if;

  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
  values (
    v_actor_id,
    'participant_deleted',
    'profile',
    p_user_id,
    jsonb_build_object('display_name', v_display_name, 'role', v_role, 'deleted_user_id', p_user_id)
  );

  delete from auth.users where id = p_user_id;

  if not found then
    raise exception 'Não foi possível excluir o usuário da autenticação.';
  end if;

  return query select v_display_name, v_avatar_path;
end;
$$;

-- ------------------------------------------------------------
-- PARTICIPANT AVATARS (PRIVATE STORAGE)
-- ------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists avatars_read_authenticated on storage.objects;
drop policy if exists avatars_admin_insert on storage.objects;
drop policy if exists avatars_admin_update on storage.objects;
drop policy if exists avatars_admin_delete on storage.objects;

-- The bucket is private. Signed-in participants may view profile photos,
-- while only an admin can create, replace or remove files.
create policy avatars_read_authenticated
  on storage.objects for select
  to authenticated
  using (bucket_id = 'avatars');

create policy avatars_admin_insert
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'avatars' and public.is_admin());

create policy avatars_admin_update
  on storage.objects for update
  to authenticated
  using (bucket_id = 'avatars' and public.is_admin())
  with check (bucket_id = 'avatars' and public.is_admin());

create policy avatars_admin_delete
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'avatars' and public.is_admin());

-- ------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.seasons enable row level security;
alter table public.rounds enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;
alter table public.audit_logs enable row level security;

-- Drop old policies so this file can be rerun safely.
drop policy if exists profiles_select_authenticated on public.profiles;
drop policy if exists profiles_admin_update on public.profiles;
drop policy if exists seasons_select_authenticated on public.seasons;
drop policy if exists seasons_admin_insert on public.seasons;
drop policy if exists seasons_admin_update on public.seasons;
drop policy if exists seasons_admin_delete on public.seasons;
drop policy if exists rounds_select_authenticated on public.rounds;
drop policy if exists rounds_admin_insert on public.rounds;
drop policy if exists rounds_admin_update on public.rounds;
drop policy if exists rounds_admin_delete on public.rounds;
drop policy if exists matches_select_authenticated on public.matches;
drop policy if exists matches_admin_insert on public.matches;
drop policy if exists matches_admin_update on public.matches;
drop policy if exists matches_admin_delete on public.matches;
drop policy if exists predictions_select_secret_until_kickoff on public.predictions;
drop policy if exists predictions_insert_own_before_kickoff on public.predictions;
drop policy if exists predictions_update_own_before_kickoff on public.predictions;
drop policy if exists predictions_delete_own_before_kickoff on public.predictions;
drop policy if exists audit_logs_select_authenticated on public.audit_logs;

create policy profiles_select_authenticated
  on public.profiles for select
  to authenticated
  using (true);

create policy profiles_admin_update
  on public.profiles for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy seasons_select_authenticated
  on public.seasons for select
  to authenticated
  using (true);
create policy seasons_admin_insert
  on public.seasons for insert
  to authenticated
  with check (public.is_admin());
create policy seasons_admin_update
  on public.seasons for update
  to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy seasons_admin_delete
  on public.seasons for delete
  to authenticated
  using (public.is_admin());

create policy rounds_select_authenticated
  on public.rounds for select
  to authenticated
  using (true);
create policy rounds_admin_insert
  on public.rounds for insert
  to authenticated
  with check (public.is_admin());
create policy rounds_admin_update
  on public.rounds for update
  to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy rounds_admin_delete
  on public.rounds for delete
  to authenticated
  using (public.is_admin());

create policy matches_select_authenticated
  on public.matches for select
  to authenticated
  using (true);
create policy matches_admin_insert
  on public.matches for insert
  to authenticated
  with check (public.is_admin());
create policy matches_admin_update
  on public.matches for update
  to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy matches_admin_delete
  on public.matches for delete
  to authenticated
  using (public.is_admin());

-- Crucial rule: admin receives NO extra read access to predictions.
create policy predictions_select_secret_until_kickoff
  on public.predictions for select
  to authenticated
  using (
    user_id = auth.uid()
    or public.match_has_started(match_id)
  );

create policy predictions_insert_own_before_kickoff
  on public.predictions for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and public.match_is_open(match_id)
  );

create policy predictions_update_own_before_kickoff
  on public.predictions for update
  to authenticated
  using (
    user_id = auth.uid()
    and public.match_is_open(match_id)
  )
  with check (
    user_id = auth.uid()
    and public.match_is_open(match_id)
  );

create policy predictions_delete_own_before_kickoff
  on public.predictions for delete
  to authenticated
  using (
    user_id = auth.uid()
    and public.match_is_open(match_id)
  );

create policy audit_logs_select_authenticated
  on public.audit_logs for select
  to authenticated
  using (true);

-- ------------------------------------------------------------
-- API GRANTS
-- ------------------------------------------------------------

revoke all on public.profiles, public.seasons, public.rounds, public.matches, public.predictions, public.audit_logs from public;
revoke all on public.profiles, public.seasons, public.rounds, public.matches, public.predictions, public.audit_logs from anon;
revoke all on public.profiles, public.seasons, public.rounds, public.matches, public.predictions, public.audit_logs from authenticated;

grant select on public.profiles to authenticated;
grant update (avatar_path) on public.profiles to authenticated;
grant select, insert, update, delete on public.seasons to authenticated;
grant select, insert, update, delete on public.rounds to authenticated;
grant select, insert, update, delete on public.matches to authenticated;
grant select, insert, update, delete on public.predictions to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on sequence public.audit_logs_id_seq to authenticated;

-- Functions can inherit EXECUTE grants from PostgreSQL PUBLIC and from
-- Supabase API-role default privileges. Revoke every client-facing default
-- explicitly, then grant only the RPCs/helpers required by signed-in users.
revoke execute on function public.handle_new_user() from public, anon, authenticated, service_role;
revoke execute on function public.is_admin() from public, anon, authenticated, service_role;
revoke execute on function public.match_has_started(uuid) from public, anon, authenticated, service_role;
revoke execute on function public.match_is_open(uuid) from public, anon, authenticated, service_role;
revoke execute on function public.guard_prediction_write() from public, anon, authenticated, service_role;
revoke execute on function public.guard_match_result() from public, anon, authenticated, service_role;
revoke execute on function public.log_prediction_activity() from public, anon, authenticated, service_role;
revoke execute on function public.log_round_created() from public, anon, authenticated, service_role;
revoke execute on function public.log_season_created() from public, anon, authenticated, service_role;
revoke execute on function public.log_match_activity() from public, anon, authenticated, service_role;
revoke execute on function public.record_login_activity() from public, anon, authenticated, service_role;
revoke execute on function public.get_prediction_presence(uuid[]) from public, anon, authenticated, service_role;
revoke execute on function public.set_active_season(uuid) from public, anon, authenticated, service_role;
revoke execute on function public.log_round_deleted() from public, anon, authenticated, service_role;
revoke execute on function public.log_season_deleted() from public, anon, authenticated, service_role;
revoke execute on function public.clear_activity_feed() from public, anon, authenticated, service_role;
revoke execute on function public.delete_participant(uuid) from public, anon, authenticated, service_role;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.match_has_started(uuid) to authenticated;
grant execute on function public.match_is_open(uuid) to authenticated;
grant execute on function public.record_login_activity() to authenticated;
grant execute on function public.get_prediction_presence(uuid[]) to authenticated;
grant execute on function public.set_active_season(uuid) to authenticated;
grant execute on function public.clear_activity_feed() to authenticated;
grant execute on function public.delete_participant(uuid) to authenticated;

-- ------------------------------------------------------------
-- DEFAULT PRIVILEGES HARDENING
-- ------------------------------------------------------------

-- Existing Supabase projects may grant API roles access to newly-created
-- objects in the public schema. Make future exposure opt-in instead.
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke execute on functions from public;

-- ------------------------------------------------------------
-- END
-- ------------------------------------------------------------

-- ------------------------------------------------------------
-- Full v1.26 feature definitions for fresh installs.
-- CHAMPIONS BOLÃO v1.26 — Sorteio de responsáveis + Pódio histórico
-- Execute uma vez no SQL Editor do Supabase.

create table if not exists public.roulette_draws (
  id uuid primary key default gen_random_uuid(),
  round_id uuid not null references public.rounds(id) on delete cascade,
  first_user_id uuid references public.profiles(id) on delete set null,
  first_display_name text not null,
  second_user_id uuid references public.profiles(id) on delete set null,
  second_display_name text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_roulette_draws_round_created
  on public.roulette_draws(round_id, created_at desc);

create table if not exists public.roulette_exclusions (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  excluded_at timestamptz not null default now(),
  excluded_by uuid references public.profiles(id) on delete set null
);

create table if not exists public.podium_champions (
  id uuid primary key default gen_random_uuid(),
  season_label text not null,
  season_sort integer not null,
  winner_order integer not null default 1 check (winner_order > 0),
  winner_name text not null,
  user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (season_label, winner_order, winner_name)
);

create index if not exists idx_podium_champions_season
  on public.podium_champions(season_sort desc, winner_order);

insert into public.podium_champions (season_label, season_sort, winner_order, winner_name)
values
  ('22/23', 2022, 1, 'Caio'),
  ('23/24', 2023, 1, 'João Pedro'),
  ('24/25', 2024, 1, 'Leandro'),
  ('24/25', 2024, 2, 'Matheus'),
  ('25/26', 2025, 1, 'Caio'),
  ('25/26', 2025, 2, 'João Pedro')
on conflict (season_label, winner_order, winner_name) do nothing;

-- Vincula automaticamente as fotos dos vencedores que também existem como
-- participantes atuais com o mesmo nome. Se não existir, a tela mantém o nome
-- e usa fallback de iniciais até que um perfil correspondente exista.
update public.podium_champions pc
set user_id = p.id
from public.profiles p
where pc.user_id is null
  and lower(trim(pc.winner_name)) = lower(trim(p.display_name));

create or replace function public.spin_round_roulette(p_round_id uuid)
returns table (
  draw_id uuid,
  round_id uuid,
  round_name text,
  first_user_id uuid,
  first_display_name text,
  first_avatar_path text,
  second_user_id uuid,
  second_display_name text,
  second_avatar_path text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_round_name text;
  v_first_id uuid;
  v_first_name text;
  v_first_avatar text;
  v_second_id uuid;
  v_second_name text;
  v_second_avatar text;
  v_draw_id uuid;
  v_created_at timestamptz;
  v_ids uuid[];
  v_names text[];
  v_avatars text[];
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Apenas administradores podem girar a roleta.';
  end if;

  select r.name into v_round_name
  from public.rounds r
  where r.id = p_round_id;

  if v_round_name is null then
    raise exception 'Rodada não encontrada.';
  end if;

  with candidates as (
    select p.id, p.display_name, p.avatar_path
    from public.profiles p
    where not exists (
      select 1
      from public.roulette_exclusions e
      where e.user_id = p.id
    )
    order by random()
    limit 2
  ), numbered as (
    select c.*, row_number() over () as rn
    from candidates c
  )
  select
    array_agg(id order by rn),
    array_agg(display_name order by rn),
    array_agg(avatar_path order by rn)
  into v_ids, v_names, v_avatars
  from numbered;

  v_first_id := v_ids[1];
  v_first_name := v_names[1];
  v_first_avatar := v_avatars[1];
  v_second_id := v_ids[2];
  v_second_name := v_names[2];
  v_second_avatar := v_avatars[2];

  if v_first_id is null or v_second_id is null then
    raise exception 'Não há dois participantes disponíveis. Redefina os participantes da roleta na Administração.';
  end if;

  insert into public.roulette_draws (
    round_id,
    first_user_id,
    first_display_name,
    second_user_id,
    second_display_name,
    created_by
  )
  values (
    p_round_id,
    v_first_id,
    v_first_name,
    v_second_id,
    v_second_name,
    auth.uid()
  )
  returning id, public.roulette_draws.created_at into v_draw_id, v_created_at;

  insert into public.roulette_exclusions (user_id, excluded_by)
  values
    (v_first_id, auth.uid()),
    (v_second_id, auth.uid())
  on conflict (user_id) do nothing;

  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, metadata)
  values (
    auth.uid(),
    'roulette_spun',
    'round',
    p_round_id,
    jsonb_build_object(
      'round_id', p_round_id,
      'round_name', v_round_name,
      'selected_user_ids', jsonb_build_array(v_first_id, v_second_id),
      'selected_names', jsonb_build_array(v_first_name, v_second_name)
    )
  );

  return query
  select
    v_draw_id,
    p_round_id,
    v_round_name,
    v_first_id,
    v_first_name,
    v_first_avatar,
    v_second_id,
    v_second_name,
    v_second_avatar,
    v_created_at;
end;
$$;

create or replace function public.reset_round_roulette()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_removed integer := 0;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Apenas administradores podem redefinir a roleta.';
  end if;

  delete from public.roulette_exclusions;
  get diagnostics v_removed = row_count;

  insert into public.audit_logs (actor_user_id, action, entity_type, metadata)
  values (
    auth.uid(),
    'roulette_reset',
    'roulette',
    jsonb_build_object('removed_participants', v_removed)
  );

  return v_removed;
end;
$$;

alter table public.roulette_draws enable row level security;
alter table public.roulette_exclusions enable row level security;
alter table public.podium_champions enable row level security;

drop policy if exists roulette_draws_select_authenticated on public.roulette_draws;
drop policy if exists roulette_exclusions_select_authenticated on public.roulette_exclusions;
drop policy if exists podium_champions_select_authenticated on public.podium_champions;

create policy roulette_draws_select_authenticated
  on public.roulette_draws for select
  to authenticated
  using (true);

create policy roulette_exclusions_select_authenticated
  on public.roulette_exclusions for select
  to authenticated
  using (true);

create policy podium_champions_select_authenticated
  on public.podium_champions for select
  to authenticated
  using (true);

revoke all on public.roulette_draws, public.roulette_exclusions, public.podium_champions from public, anon, authenticated;
grant select on public.roulette_draws, public.roulette_exclusions, public.podium_champions to authenticated;

revoke execute on function public.spin_round_roulette(uuid) from public, anon, authenticated, service_role;
revoke execute on function public.reset_round_roulette() from public, anon, authenticated, service_role;
grant execute on function public.spin_round_roulette(uuid) to authenticated;
grant execute on function public.reset_round_roulette() to authenticated;
